### ISSUE TITLE
Standalone CRISPRedict

### ISSUE THREAD

**Issue by harmveer** [VKonstantakos/CRISPRedict#1]
Hi! 

I was interested in looking at the standalone version of CRISPRedict as described in your recent NAR paper (https://doi.org/10.1093/nar/gkac466), but it appears not to be uploaded on this repository. Where can I find it?

Best,
Harm

**Comment by VKonstantakos** [comment]
Hello, thank you for your interest in CRISPRedict.

You can now find the source code corresponding to the current version of the Web Server's models on this repository.

The trained models can be found in the "Saved models" folder. Notebook examples are also provided to reproduce our results and illustrate their usage.

Let me know if anything else is needed.

Vasilis
